[project]
name = "trade-optimisation-data-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "streamlit==1.42.0",
    "dill==0.3.9",
    "numpy==2.2.3",
    "watchdog==6.0.0",
    "plotly==5.22.0",
]
